### ISSUE TITLE
目前此工具存在的问题

### ISSUE THREAD

**Issue by QiangJi** [yty/reacTIVision#3]
@xiajiaonly 
1.  此工具的原版在窗口的初始化时，指定摄像机的分辨率为多大窗口的大小就为多大。为了方便应用程序使用，我在sonovo的分支进行了修改，目前此工具支持海康网络相机，但是分辨率只能支持2048_1536，工具的窗口只能支持1024_768。当时为了尽快测试，才把工具做的如此不灵活。
2. 此工具目前不支持隐藏窗口和托盘的功能。

**Comment by yty** [comment]
以后会从直接购买1024x768的海康设备来解决问题1。
问题2由接下来的开发者添加。
